### PR TITLE
Visual essay layout sam low

### PR DESCRIPTION
**Pull request by SamuelmdLow**
In my meeting with Annabella she asked if the visual essay could be added to the website so that writers could experiment with it and give feedback.

The visual essay template allows for more focus to be on images by having the images stay static on the left side of the page while the reader scrolls text on the right.

### CODE REVIEW

**Review by FireBoyAJ24 — DISMISSED** [review]
The images overlap the footer

**Comment by SamuelmdLow** [comment]
The visual essay is a block in the content streamfield but it only displays well in the visual essay template that I made or the full width template

**Comment by SamuelmdLow** [comment]
Merge audio quote block

**Comment by SamuelmdLow** [comment]
Pull from develop

**Comment by SamuelmdLow** [comment]
Finished!

**Comment by SamuelmdLow** [comment]
When reviewing, make sure you use the visual essay layout. The visual essay block looks really bad in other layouts

**Comment by SamuelmdLow** [comment]
I think this branch is ready to be reviewed

**Comment by SamuelmdLow** [comment]
merged into redesign

**Pull request closed without merging**
